services:
  api:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: amo-edna-api
    environment:
      - EDNA_API_KEY=a564b2c3-1d3f-43e9-bc00-22a7d9580216
      - EDNA_BASE_URL=https://app.edna.ru
      - EDNA_IM_TYPE=whatsapp
      - EDNA_STATUS_CALLBACK_URL=https://amo-edna.24tema.ru/webhooks/edna
      - EDNA_IN_MESSAGE_CALLBACK_URL=https://amo-edna.24tema.ru/webhooks/edna
      - EDNA_MESSAGE_MATCHER_CALLBACK_URL=https://amo-edna.24tema.ru/webhooks/edna
      - EDNA_CASCADE_ID=4567

      - AMOCRM_AMOJO_BASE_URL=https://amojo.amocrm.ru
      - AMOCRM_CHANNEL_ID=09747b7f-c6d3-4ee3-bfc3-a0db8550c34d
      - AMOCRM_CHANNEL_SECRET=2c1249562257eb6b81a8427c7f2d2189f3d008de
      - AMOCRM_ACCOUNT_ID=d1987892-f0ef-4b43-aa1e-8f1e114565dc
      - AMOCRM_CONNECT_TITLE=Integration Channel
      - AMOCRM_HOOK_API_VERSION=v2
    ports:
      - "28000:8000"
    volumes:
      - ./src:/app
    restart: unless-stopped
